version: "3.7"

services:
  host:
    image: host
    container_name: docker-host
    hostname: docker-host
    restart: unless-stopped
    ports:
      # This port (1337) is only used by neo4j-shell, Sails.js, and WASTE Encrypted File Sharing
      # This means that host collisions are very unlikely.
      - "1337:22"
    build:
      context: ./containers/host/
      args:
        - ARG_USER_ID=${USER_ID}
        - ARG_GROUP_ID=${GROUP_ID}
        - ARG_UBUNTU_VERSION=${UBUNTU_VERSION}
    volumes: &host-volumes
      - ./config/hosts:/etc/hosts
      - type: bind
        source: ${DATA_DIR}
        target: /mnt/data
      - type: bind
        source: ${USER_SSH_DIR:-/tmp}
        target: /home/development/.ssh
      - type: bind
        source: ${USER_CACHE_DIR:-/tmp}
        target: /home/development/.cache
      - type: bind
        source: ./logs
        target: /var/log
      - type: bind
        source: ./shared
        target: /shared

  container-mysql:
    image: container:mysql${MYSQL_VERSION}
    container_name: mysql${MYSQL_VERSION}
    hostname: mysql
    restart: unless-stopped
    working_dir: /var/lib/mysql
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    build:
      context: ./containers/mysql/
      args:
        - ARG_USER_ID=${USER_ID}
        - ARG_GROUP_ID=${GROUP_ID}
        - ARG_MYSQL_VERSION=${MYSQL_VERSION:-latest}
    volumes:
      # We can support persistent storage at the cost of losing our host volumes
      - ./containers/mysql/database:/var/lib/mysql
    depends_on:
      - host

  container-php:
    image: container:php${PHP_VERSION}
    container_name: php${PHP_VERSION}
    hostname: php
    restart: unless-stopped
    working_dir: /var/www
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./containers/php/
      args:
        - ARG_USER_ID=${USER_ID}
        - ARG_GROUP_ID=${GROUP_ID}
        - ARG_PHP_VERSION=${PHP_VERSION:-latest}
        - ARG_DEVLIBS=${DEVLIBS:-}
        - ARG_ENABLE_PREINSTALLED=${ENABLE_PREINSTALLED:-}
        - ARG_PHP_MODULES=${PHP_MODULES:-}
        - ARG_PECL_MODULES=${PECL_MODULES:-}
    volumes: *host-volumes
    depends_on:
      - host
