container-host:
  image: container:host
  container_name: ${INSTANCE_NAME}docker-host
  hostname: docker-host
  restart: unless-stopped
  build:
    context: ./
    dockerfile: ./containers/host/Dockerfile
    network: host
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/hosts:/etc/hosts:ro
    - data:/mnt/data
    - cache:/home/development/.cache
    - config:/home/development/.config
    - ssh:/home/development/.ssh
    - history_file:/home/development/.bash_history
    - logs:/var/log
    - shared:/shared
