host:
  image: host
  container_name: ${INSTANCE_NAME}docker-host
  hostname: docker-host
  restart: unless-stopped
  ports:
    # This port (1337) is only used by neo4j-shell, Sails.js, and WASTE Encrypted File Sharing
    # This means that host collisions are very unlikely.
    - "1337:22"
  build:
    context: ./containers/host/
    args:
      - ARG_USER_ID=${USER_ID}
      - ARG_GROUP_ID=${GROUP_ID}
      - ARG_UBUNTU_VERSION=${UBUNTU_VERSION}
  volumes: &host-volumes
    - ./config/hosts:/etc/hosts
    - type: bind
      source: ${DATA_DIR}
      target: /mnt/data
    - type: bind
      source: ${USER_SSH_DIR:-/tmp}
      target: /home/development/.ssh
    - type: bind
      source: ${USER_CACHE_DIR:-/tmp}
      target: /home/development/.cache
    - type: bind
      source: ./logs
      target: /var/log
    - type: bind
      source: ./shared
      target: /shared
