container-mysql:
  image: container:mysql${MYSQL_VERSION}
  container_name: mysql${MYSQL_VERSION}
  hostname: mysql
  restart: unless-stopped
  working_dir: /var/lib/mysql
  network_mode: host
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  ports:
    - "3306:3306"
  build:
    context: ./containers/mysql/
    args:
      - ARG_USER_ID=${USER_ID}
      - ARG_GROUP_ID=${GROUP_ID}
      - ARG_MYSQL_VERSION=${MYSQL_VERSION:-latest}
  volumes:
    # We can support persistent storage at the cost of losing our host volumes
    - ./containers/mysql/database:/var/lib/mysql
  depends_on:
    - host
