container-php:
  image: container:php${PHP_VERSION}
  container_name: php${PHP_VERSION}
  hostname: php
  restart: unless-stopped
  working_dir: /var/www
  network_mode: host
  ports:
    - "80:80"
    - "443:443"
  build:
    context: ./containers/php/
    args:
      - ARG_USER_ID=${USER_ID}
      - ARG_GROUP_ID=${GROUP_ID}
      - ARG_PHP_VERSION=${PHP_VERSION:-latest}
      - ARG_DEVLIBS=${DEVLIBS:-}
      - ARG_ENABLE_PREINSTALLED=${ENABLE_PREINSTALLED:-}
      - ARG_PHP_MODULES=${PHP_MODULES:-}
      - ARG_PECL_MODULES=${PECL_MODULES:-}
  volumes: *host-volumes
  depends_on:
    - host
